 apiVersion: v1
 kind: PersistentVolume
 metadata:
   name: trow-data-hostpath-pv
   labels:
     app: trow
 spec:
   accessModes:
   - ReadWriteOnce
   capacity:
     storage: 10Gi
   hostPath:                     <<<<< on defini ici hostpath comme type de stockage : on va créer sur nos nodes le repertoire /data qui sera le point de montage. Attention il peut etre necessaire d'adapter les droits de users uid / gid qui doivent accceder depuis le container au repertoire du hosts.
     path: /data

