 apiVersion: v1
 kind: PersistentVolume
 metadata:
   name: trow-hostpath-pv
   labels:
     app: trow
 spec:
   accessModes:
   - ReadWriteOnce
   capacity:
     storage: 10Gi
   hostPath:
     path: /data

