replicaCount: 1
securityContext:
  runAsUser: 65534        
  runAsGroup: 65534
image:
  repository: artifact-docker-lapin.net/prometheus-exporter/prometheus-proxmox-exporter
  pullPolicy: IfNotPresent
  tag: "0.1"

serviceMonitor:
  enabled: true      
  selector:
    release: monitoring          
  serviceLabel: "proxmox"
  interval: 30s
  scrapeTimeout: 10s

secret:
  name: proxmox-api        
