apiVersion: v1
kind: Pod
metadata:
  name: debian-pod
spec:
  containers:
    - image: artifact-docker-infra.meetic.ilius.net/debian-utils:1
      name: debian
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
