cat Chart.yaml
apiVersion: v2
description: A Helm chart for logging stack in lapin env
home: https://www.elastic.co/products
icon: https://www.elastic.co/assets/bltb35193323e8f1770/logo-elasticstack-lt.svg
name: ilius-logging-stack
version: 0.0.1
appVersion: 1.0.0
maintainers:
- name: lapin
  email: lapin@lapin.net
dependencies:
- name: elasticsearch
  version: 7.12.0
  repository: https://artifact.lapin.net/artifactory/helm-remote-stable/
  condition: elasticsearch.enabled
- name: kibana
  version: 7.12.0
  repository: https://artifact.lapin.net/artifactory/helm-remote-stable/
  condition: kibana.enabled
- name: filebeat
  version: 7.12.0
  repository: https://artifact.lapin.net/artifactory/helm-remote-stable/
  condition: filebeat.enabled
- name: fluent-bit
  version: 0.15.4
  repository: https://artifact.lapin.net/artifactory/helm-remote-stable/
  condition: fluent-bit.enabled

