#!/usr/bin/env python
import string, sys
if len(sys.argv) == 1 :
  print 'Converti un IPv4 en hexa pour PXE'
  print '''Exemple :
bash# ip2hex 10.4.44.10
0A042C0A
'''
elif len(sys.argv) == 2 :
  a = sys.argv[1].split('.')
  print "".join([hex(int(value))[2:].zfill(2) for value in a]).upper()

else:
  print 'Trop d\'arguments !!'
