apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-pve-exporter-hypervisor
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus-pve-exporter
subsets:
- addresses:
{{ toYaml .Values.nodeExporter.nodeExporterTarget | indent 4 }}

