apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pve-exporter
  namespace: {{.Release.Namespace}}
  labels:
    release:  {{ .Release.Name }}
    exporter: {{ .Values.serviceMonitor.serviceLabel }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 9221
      targetPort: pve-exporter
      protocol: TCP
      name: pve-exporter
