---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "lapin-proxmox-monitoring.name" . }}
    chart: {{ template "lapin-proxmox-monitoring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  pve.yml: |-
    default:
      user: {{ .Values.pveExporter.user }}
      password: {{ .Values.pveExporter.password }}
      verify_ssl: false
