apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}        
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: pve-exporter
              containerPort: 9221
          command: ["/usr/local/bin/pve_exporter", "/config/pve.yml"]
          livenessProbe:
            httpGet:
              path: /
              port: pve-exporter
            initialDelaySeconds: 15
            timeoutSeconds: 15      
          readinessProbe:
            httpGet:
              path: /
              port: pve-exporter
            initialDelaySeconds: 15
            timeoutSeconds: 30
          volumeMounts:
          - name: proxmox-api-vol
            mountPath: "/config"
            readOnly: true
      volumes:
      - name: proxmox-api-vol
        secret:
          secretName: {{ .Values.secret.name }}
            
