prometheus:
 service:
   port: 80      
   type: LoadBalancer
alertmanager:
 service:
   port: 80      
   type: LoadBalancer

grafana:
  persistence:
    enabled: false
  service:
    port: 80 
    type: LoadBalancer
coreDns:
  enabled: true

kubeDns:
  enabled: false
