prometheus:
 ingress:
   enabled: true
   annotations:
     kubernetes.io/ingress.class: nginx
   hosts:
   - "prometheus.boogie7.net"
 service:
   externalIPs: 
   - 192.168.0.82

alertmanager:
 ingress:
   enabled: true
   annotations:
     kubernetes.io/ingress.class: nginx
   hosts:
   - "alertmanager.boogie7.net"
 service:
   externalIPs:
   - 192.168.0.82

grafana:
  persistence:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - "grafana.boogie7.net"
  service:
    externalIPs: 
    - 192.168.0.82
coreDns:
  enabled: true

kubeDns:
  enabled: false
