{
 "title": "proxmox - pve - hypervisor",
 "description": "Proxmox Virtual Environment Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Cluster",
    "query": "label_values(pve_node_info, job)"
   },
   {
    "name": "instance",
    "query": "label_values(pve_node_info{job=\"$job\"}, instance)"
   },
   {
    "name": "node",
    "query": "label_values(pve_storage_info{job=\"$job\"},node)"
   }
  ]
 },
 "panels": [
  { "title": "Cpu - usage node view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host CPU -   $node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "repeat": "node",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=\"$instance\",id=\"node/$node\" } / pve_cpu_usage_limit and on(id) pve_node_info"
    }
   ]
  },
  {
   "title": "Cpu - usage details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host cpu % usage - $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "repeat": "node",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pve_cpu_usage_ratio{instance=\"$instance\",id=\"node/$node\" } / pve_cpu_usage_limit and on(id) pve_node_info"
      }
     ]
    },
    {
     "title": "Guest cpu % usage - $node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "repeat": "node",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((pve_cpu_usage_ratio{instance=\"$instance\"} / pve_cpu_usage_limit) * on(id, instance ) group_left(name, type, node) pve_guest_info{node=\"$node\"}) and on(id, instance ) pve_up == 1",
       "legendFormat": "{{name}} - {{id}} - {{node}}"
      }
     ]
    }
   ]
  },
  { "title": "Memory - usage node view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Host Memory - $node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "repeat": "node",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\", id=\"node/$node\"} / pve_memory_size_bytes and on(id) pve_node_info"
    }
   ]
  },
  {
   "title": "Memory - usage details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host memory % usage - $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "repeat": "node",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pve_memory_usage_bytes{instance=\"$instance\", id=\"node/$node\"} / pve_memory_size_bytes and on(id) pve_node_info"
      }
     ]
    },
    {
     "title": "Guest memory % usage - $node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "repeat": "node",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes * on(id, instance) group_left(name, type, node) pve_guest_info{node=\"$node\"}) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} - {{id}} - {{node}}"
      }
     ]
    }
   ]
  },
  { "title": "Disk - usage node view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Host Disk - $node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "repeat": "node",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{instance=\"$instance\", id=\"node/$node\"} / pve_disk_size_bytes and on(id) pve_node_info",
     "legendFormat": "$node"
    }
   ]
  },
  {
   "title": "Disk - usage details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host disk % usage  - $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "repeat": "node",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pve_disk_usage_bytes{instance=\"$instance\", id=\"node/$node\"} / pve_disk_size_bytes and on(id) pve_node_info"
      }
     ]
    },
    {
     "title": "Guest disk % usage - $node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "repeat": "node",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pve_disk_usage_bytes{instance=\"$instance\"} / pve_disk_size_bytes{instance=\"$instance\"} * on (id, instance) group_left(name, type, node) pve_guest_info{node=\"$node\"}",
       "legendFormat": "{{name}} - {{id}} - {{node}}"
      }
     ]
    },
    {
     "title": "Guest disk  I/O rate ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "repeat": "node",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "((rate(pve_disk_write_bytes{instance=\"$instance\"}[5m]) + rate(pve_disk_read_bytes[5m])) * on(id, instance) group_left(name,node, type) pve_guest_info{node=\"$node\"}) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} - {{id}} - {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - usage details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Guest network  IO/s rate - $node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "repeat": "node",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(rate(pve_network_receive_bytes{instance=\"$instance\"}[5m]) * on(id, instance) group_left(name, type, node) pve_guest_info{node=\"$node\"}) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} RECV ({{type}}) - {{node}}"
      },
      {
       "expr": "(rate(pve_network_transmit_bytes{instance=\"$instance\"}[5m])* on(id, instance) group_left(name, type, node) pve_guest_info{node=\"$node\"}) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} SEND  ({{type}}) - {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources allocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource node allocation summary ",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum by (id, name, node ) (pve_guest_info{instance=\"$instance\", node=~\"$node\",template!=\"1\"})"
      },
      {
       "expr": "sum by (id) (pve_up{instance=\"$instance\",template!=\"1\"} and on (id, instance) pve_guest_info)"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_limit{instance=\"$instance\",template!=\"1\"} and on (id, instance) pve_guest_info)"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_ratio{instance=\"$instance\",template!=\"1\"} / pve_cpu_usage_limit and on (id, instance) pve_guest_info)"
      },
      {
       "expr": "sum by (id) (pve_memory_size_bytes{instance=\"$instance\",template!=\"1\"} and on (id, instance) pve_guest_info)"
      },
      {
       "expr": "sum by (id) (pve_memory_usage_bytes{instance=\"$instance\",template!=\"1\"} / pve_memory_size_bytes and on (id, instance) pve_guest_info)"
      },
      {
       "expr": "sum by (id) (pve_disk_size_bytes{instance=\"$instance\",template!=\"1\"} and on (id, instance) pve_guest_info)"
      },
      {
       "expr": "sum by (id) (pve_disk_usage_bytes{instance=\"$instance\",template!=\"1\"} / pve_disk_size_bytes and on (id, instance) pve_guest_info)"
      }
     ]
    }
   ]
  },
  {
   "title": "Usages - count / stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Guests CPU usage - cluster wide",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((pve_cpu_usage_ratio{instance=\"$instance\"} / pve_cpu_usage_limit) * on(id, instance) group_left(name, type, node) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} ({{type}})  - {{node}}"
      }
     ]
    },
    {
     "title": "Guests memory usage  - cluster wide",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes * on(id, instance) group_left(name, type, node) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} ({{type}}) - {{node}}"
      }
     ]
    },
    {
     "title": "Guests Disk usage - cluster wide",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pve_disk_usage_bytes{instance=\"$instance\"} / pve_disk_size_bytes{instance=\"$instance\"} * on (id, instance) group_left(name, type, node) pve_guest_info",
       "legendFormat": "{{name}} ({{type}}) -  {{node}}"
      }
     ]
    },
    {
     "title": "Network IO/s - cluster wide",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(rate(pve_network_receive_bytes{instance=\"$instance\"}[5m]) * on(id, instance) group_left(name, type, node) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} RECV ({{type}}) - {{node}}"
      },
      {
       "expr": "(rate(pve_network_transmit_bytes{instance=\"$instance\"}[5m])* on(id, instance) group_left(name, type, node) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} SEND ({{type}}) - {{node}}"
      }
     ]
    },
    {
     "title": "Disk IO/s - cluster wide",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "((rate(pve_disk_write_bytes{instance=\"$instance\"}[5m]) + rate(pve_disk_read_bytes[5m])) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} ({{type}})"
      }
     ]
    }
   ]
  }
 ]
}