---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "prometheus-proxmox-exporter.name" . }}
    chart: {{ template "prometheus-proxmox-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  pve.yml: |-
    default:
     user: pve_monit@pve                                                                         
     password: blabla
     verify_ssl: false
