apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{.Release.Namespace}}  
  labels:
    exporter: proxmox      
spec:
  selector:
    app: {{ .Chart.Name }}      
  ports:
    - port: 9221
      targetPort: pve-exporter
      protocol: TCP
      name: pve-exporter
