---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: net-svc-b-k   
      protocol: layer2             # on defini ici le mode d'utilisation de metallb : ici layer2 : on passe par la couche mac adresse des nodes pour diriger le traffic.
      addresses:
      - 192.168.0.90-192.168.0.95  # ici on defini une plage ip qui sert à nos services 
