---
# reload php process ONLY for redhat satelite version 
- name: reload nginx process
  # got to provide correct name(s) ...
  hosts : all
  become: yes 

  tasks:  
    - name: service reload
      service: name=rh-nginx18-nginx state=reloaded

