---
# reload php process ONLY for redhat satelite version 
- name: reload php-fpm process
  # got to provide correct name(s) ...
  hosts : all
  become: yes 

  tasks:  
    - name: service reload
      service: name=rh-php56-php-fpm state=reloaded

