- hosts: all
  become: yes
  tasks:

    - name: Installing mandatory packages.
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'vim' , 'curl', 'tree', 'sudo', 'fail2ban', 'haveged', 'gnupg2', 'openssl', 'python3-pip', 'qemu-guest-agent', 'software-properties-common', 'netcat', 'mtr', 'dnsutils', 'tcputils', 'wget']

    - name: create the 'boogie' user
      user: name=boogie append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'boogie' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'boogie ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the boogie user
      authorized_key: user=boogie key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
