---
- hosts: k-master01
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: vars.yml

      - name: Initializing Kubernetes on the master.
        become: yes
        shell: kubeadm init --pod-network-cidr={{ calico_cidr }}/16 --ignore-preflight-errors=all

      - name: create .kube directory
        become: yes
        become_user: boogie
        file:
          path: $HOME/.kube
          state: directory
          mode: 0755

      - name: copy admin.conf to user's kube config
        copy:
         src: /etc/kubernetes/admin.conf
         dest: /home/boogie/.kube/config
         remote_src: yes
         owner: boogie

      - name: Downloading the Calico Pod Network manifest.
        get_url:
            url: "{{ calico_policy_url }}"
            dest: /tmp/calico.yml

      - name: Modifying the Pod network CIDR for Calico.
        replace:
            path: /tmp/calico.yml
            regexp: 192.168.0.0
            replace: "{{ calico_cidr }}"

      - name: Applying the Calico Pod Network to Kubernetes.
        become: yes
        become_user: boogie
        shell: kubectl apply -f /tmp/calico.yml

      - name: Deleting the Calico Pod Network manifest from disk.
        file: 
            path: /tmp/calico.yml
            state: absent
