- hosts: k-master01
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.124.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: boogie
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/boogie/.kube/config
        remote_src: yes
        owner: boogie

    - name: install Pod network
      become: yes
      become_user: boogie
      shell: kubectl apply -f https://docs.projectcalico.org/v3.8/getting-started/kubernetes/installation/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml>> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
