- hosts: masters
  become: yes
  gather_facts: false
  tasks:
    - name: Retrieve kubeadm join command to be used next by workers nodes
      shell: kubeadm token create --print-join-command
      when: k8s_join_command is undefined
      register: k8s_join_command


- hosts: workers
  become: yes
  tasks:
    - name:  set workers in cluster  with dedicated master  token 
      shell: "{{ hostvars[groups['masters'][0]]['k8s_join_command']['stdout'] }}"
