#!/bin/sh
####################################
## THIS FILE IS MANAGED BY PUPPET ##
####################################

export HTTP_PROXY=vip-proxy.secu.common.prod.vit.e-merchant.net:3128
export COMPOSER_HOME="/usr/local/composer" 
/usr/bin/php5 /usr/local/composer/composer.phar $@
