#!/bin/sh
# append local packages to the build environment

apt-get install apt-utils
(cd $BUILDRESULT; apt-ftparchive packages . >Packages)
echo "deb file://$BUILDRESULT/ ./" >/etc/apt/sources.list.d/build.list
apt-get update
