#!/bin/sh

SVN_USER='svn-autoupdate'
SVN_PASSWD='MxuhRo44rUCXv7mY'

SVN_ARGS="--no-auth-cache --non-interactive --username $SVN_USER --password $SVN_PASSWD"

export LANG=en_US.utf8

# Update SVN
su common -c "svn update $SVN_ARGS ~/web_dir/php-documentation/src/* >/dev/null"

# Generate documentation
su common -c "cd ~/web_dir/php-documentation ; /usr/bin/php ~/web_dir/php-documentation/update_doxygen.php src/* >/dev/null"

# vim: ts=4 sw=4 et
