#!/bin/bash

# exit on all errors
set -e

PUPPET='puppet01.cms.common.prod.dc3.e-merchant.net'
USER='scmsynchro'

ssh ${USER}@${PUPPET} '/usr/local/bin/svnup-norel-puppet-cms'

PUPPET='puppet401.cms.common.prod.dc3.e-merchant.net'
USER='scmsynchro'

ssh ${USER}@${PUPPET} '/usr/local/bin/svnup-norel-puppet-cms'

exit $?

