#!/bin/bash

# vim: sw=4 et ts=4

# dlarquey
# Wrapper for cssh client, to use with an auto update cssh configuration


# /usr/bin/cssh -l root -o "-o StrictHostKeyChecking=no" web_front_dsg_vit_ALL


CSSH_CONFIG_FILE=~/.csshrc
CSSH=/usr/bin/cssh
CSSH_CLUSTER_CONFIG_FILE=$HOME/.csshrc_clusters_dns2cssh_dns2cssh # specify your cssh extra cluster file


# Functions

function logError {
    echo "ERROR: $@" >&2
    exit 1
}

function syntax() {
    echo "Wrapper for cssh client."
    echo "This script could list clusters defined in an extra config file"
    echo
    echo "SYNTAX:"
    echo -e "\t$0 [list REGEXP_CLUSTER] [hosts CLUSTER] <CSSH_OPTS>\n"
    exit
}

function check_age() {
    [ -n $1 -a -f $1 ] || return
    age=$(($(date +%s) - $(stat -c %Y $1)))
    if [ -z $age -o $age -ge $((7*86400)) ]; then
        echo "Cssh config file is older than 1 week."
        echo -n "Continue (y/n): "
        read
        [ -z $REPLY -o $REPLY != "y" ] && exit 1
    fi
}



# MAIN

[ -z "$1" ] && syntax
[ -x $CSSH ] || logError "Missing cssh client"
[ -f $CSSH_CONFIG_FILE ] || logError "Missing cssh config file: $CSSH_CONFIG_FILE"

case "$1" in
    list)
        [ -n $CSSH_CLUSTER_CONFIG_FILE -a -f $CSSH_CLUSTER_CONFIG_FILE ] || logError "cssh wrapper: Can't find cluster config file"
        check_age $CSSH_CLUSTER_CONFIG_FILE
        if [ -z "$2" ]; then
            echo "# CSSH clusters list"
            egrep -- "^clusters[[:blank:]]*=" $CSSH_CLUSTER_CONFIG_FILE|sed s/^clusters[[:blank:]]*=//|xargs -n 1
        else
            echo "# CSSH clusters list matching pattern: <$2>"
            egrep -- "^clusters[[:blank:]]*=" $CSSH_CLUSTER_CONFIG_FILE|sed s/^clusters[[:blank:]]*=//|xargs -n 1|egrep "$2"
        fi
    ;;
    host|hosts)
        [ -n $CSSH_CLUSTER_CONFIG_FILE -a -f $CSSH_CLUSTER_CONFIG_FILE ] || logError "cssh wrapper: Can't find cluster config file"
        check_age $CSSH_CLUSTER_CONFIG_FILE
        echo "# Hosts defined for CSSH cluster: <$2>"
        egrep -q "^clusters[[:blank:]]*=.*[[:blank:]]+$2([[:blank:]]+|$)" $CSSH_CLUSTER_CONFIG_FILE || logError "Can't find cluster: $2"
        egrep -- "^$2[[:blank:]]*=" $CSSH_CLUSTER_CONFIG_FILE|sed s/^$2[[:blank:]]*=//|xargs -n 1
    ;;
    help|--help|-h)
        syntax
    ;;
    *)
        check_age $CSSH_CLUSTER_CONFIG_FILE
        /usr/bin/cssh $@
esac

