#!/bin/bash

user=${1:-$USER}
bastion=${2}
tmux_session="wmaster"

if ! which tmux > /dev/null
then
    echo "Error: tmux not found ! Exiting..." >&2
    exit 1
fi

if tmux has-session -t $tmux_session 2>/dev/null
then
    tmux attach -t $tmux_session
else
    tmux new -s $tmux_session bash -c "
( while true; do sleep 60; tmux send-keys -t $tmux_session 'date'; tmux send-keys -t $tmux_session Enter; done ) &
ka_pid=\$! &
ssh -t -A -M -S ~/.ssh/wallix.sock ${user}@wallix ${user}@${bastion}:SSH
kill \$ka_pid"
fi
