apiVersion: apps/v1
kind: StatefulSet
metadata:
 labels:
  app: mariadb
 name: mariadb
spec:
 serviceName: mariadb
 selector:
  matchLabels:
   app: mariadb
 template:
  metadata:
   labels:
    app: mariadb
  spec:
   containers:
    - image: mariadb
      name: mariadb
      imagePullPolicy: IfNotPresent
      # declaration du pooint de montage pour le volume déclaré précedemment : 
      volumeMounts:
       - mountPath: /var/lib/mysql
         name: mariadb-data
      # declaration de variables nécéssaires pour le demarrage de mysql    
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: mot-de-passe-root
 # ici on declare un template de volume qui permettra a chaque pod ayant besoin de stockage d'avoir un volume dédié portant un id unique. L'object de type persistant volume claim sera créer automatiquement par le statefulset 
 volumeClaimTemplates:
  - metadata:
     name: mariadb-data
    spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
      requests:
       storage: 100Mi
