---
monitoring:
  namespace: 'prometheus-operator'
  dashboard: true
#
traefik:
  imageTag: 2.4
  nodeSelector:
    'node-role.kubernetes.io/ingress': 'true'
  loadBalancerIP: '192.168.7.7'  
  externalIP: '192.168.7.7'
  # dashboard section : 
  dashboard:
    enabled: true
    domain: dashlb.prod.lapin.io
    ingress:
      annotations:
        kubernetes.ingressClass: traefik
        external-dns.alpha.kubernetes.io/hostname: dashlb.prod.lapin.io.
        external-dns.alpha.kubernetes.io/ttl: "10"
  # main spec behaviour         
  kubernetes:
    ingressEndpoint:
      ip: '192.168.7.7'
  metrics:
    prometheus:
      enabled: true
    serviceMonitor:
      enabled: true

