alertmanager:
 ingress:
  enabled: true
  annotations:
   kubernetes.io/ingress.class: nginx
  hosts:
   - "alertmanager.boogie.nip.io"
grafana:
 persistence:
  enabled: true
 ingress:
  enabled: true
  annotations:
   kubernetes.io/ingress.class: nginx
  hosts:
   - "grafana.boogie.nip.io"
coreDns:
 enabled: false
kubeDns:
 enabled: true
