apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: prometheus-node-exporter
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
  sessionAffinity: None
  type: ClusterIP

