apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-node-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus-node-exporter
subsets:
- addresses:
{{ toYaml .Values.nodeExporter.nodeExporterTarget | indent 4 }}
  ports:
  - name: node-exporter
    port: 9100
    protocol: TCP

