{{- if .Values.nodeExporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-node-exporter-metrics
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.serviceMonitor.selector | indent 4 }}
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: node-exporter
    scrapeTimeout: 10s
  jobLabel: prometheus-node-exporter
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  {{ toYaml .Values.nodeExporter.serviceMonitor.selector | indent 4 }}
{{- end }}
