---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - my-asn: 65002
      peer-asn: 65001
      peer-address: 192.168.0.7
    address-pools:
    - name: net-svc-b-k    
      protocol: bgp
      addresses:
      - 10.127.0.1-10.127.0.100      

