---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "proxmox-monitoring.name" . }}
    chart: {{ template "proxmox-monitoring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  pve.yml: |-
    default:
     user: pve_exporter@pve
     password: {{ .Values.proxmox_api_pwd }}
     verify_ssl: false

