# proxmox pve section : proxmox api to monitor vms on cluster :
monitoring:
  dashboard: true

replicaCount: 1
securityContext:
  runAsUser: 65534
  runAsGroup: 65534
image:
  repository: artifact-docker.lapin.net/prometheus-exporter/prometheus-proxmox-exporter
  pullPolicy: IfNotPresent
  tag: "0.1"

serviceMonitor:
  enabled: true
  selector:
    release: monitoring
  serviceLabel: "proxmox"
  interval: 30s
  scrapeTimeout: 10s

secret:
  name: proxmox-api

# proxmox node exporter section : hosts  part of the cluster
nodeExporter:
  serviceMonitor:
    enabled: true
    selector:
      app: prometheus-node-exporter
    serviceLabel: "node-exporter"
    interval: 30s
    scrapeTimeout: 10s
