apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: registry.lapin.io
  namespace: harbor
spec:
  # Secret names are always required.
  secretName: registry-tls
  duration: 5160h # 90d
  renewBefore: 360h # 15d
  organization:
  - bob
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: registry.lapin.io
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, USI SAN, or IP address is required.
  dnsNames:
  - registry.lapin.io
  - core.registry.lapin.io
  - notary.registry.lapin.io
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io

